name: Build LLVM for Jailbreak iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Clone iOS SDK
      run: |
        git clone https://github.com/xybp888/iOS-SDKs.git
        ls -la iOS-SDKs/
        echo "SDKROOT=$(pwd)/iOS-SDKs/iPhoneOS16.5.sdk" >> $GITHUB_ENV
    - name: Clone LLVM
      run: |
        git clone --depth 1 https://github.com/llvm/llvm-project.git
        cd llvm-project
        git fetch --depth 1 origin main
        git checkout main
    - name: Configure
      run: |
        mkdir build && cd build
        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_SYSTEM_NAME=iOS \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=16.5 \
          -DCMAKE_OSX_ARCHITECTURES="arm64" \
          -DCMAKE_SYSROOT="$SDKROOT" \
          -DLLVM_ENABLE_PROJECTS="clang;lld" \
          -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
          -DLLVM_TARGETS_TO_BUILD="AArch64" \
          ../llvm-project/llvm
    - name: Build
      run: |
        cd build
        ninja clang lld
    - name: Package
      run: |
        cd build
        mkdir -p package/usr/local/bin
        cp bin/clang bin/clang++ bin/lld package/usr/local/bin/
        tar -czf llvm-for-ios.tar.gz -C package .
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: llvm-for-ios
        path: build/llvm-for-ios.tar.gz
