name: Build LLVM(clang/++, lld) for Jailbreak iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Clone iOS SDK
      run: |
        git clone https://github.com/xybp888/iOS-SDKs.git
        echo "SDKROOT=$(pwd)/iOS-SDKs/iPhoneOS16.5.sdk" >> $GITHUB_ENV

    - name: Clone LLVM
      run: |
        git clone --depth 1 https://github.com/llvm/llvm-project.git

    - name: Build Native TableGen
      run: |
        mkdir build-native
        cd build-native
        unset SDKROOT
        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_TARGETS_TO_BUILD="AArch64" \
          -DLLVM_ENABLE_PROJECTS="clang;lld" \
          ../llvm-project/llvm
        ninja -j$(sysctl -n hw.ncpu) llvm-tblgen clang-tblgen

    - name: Configure Cross Build
      run: |
        mkdir build && cd build
        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_SYSTEM_NAME=iOS \
          -DCMAKE_OSX_SYSROOT="$SDKROOT" \
          -DCMAKE_OSX_ARCHITECTURES="arm64" \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=16.5 \
          -DCMAKE_SYSTEM_PROCESSOR=arm64 \
          -DCMAKE_CROSSCOMPILING=ON \
          -DCMAKE_C_COMPILER_WORKS=ON \
          -DCMAKE_CXX_COMPILER_WORKS=ON \
          -DLLVM_HOST_TRIPLE=arm64-apple-darwin \
          -DLLVM_DEFAULT_TARGET_TRIPLE=arm64-apple-ios16.5 \
          -DLLVM_TABLEGEN=$(pwd)/../build-native/bin/llvm-tblgen \
          -DCLANG_TABLEGEN=$(pwd)/../build-native/bin/clang-tblgen \
          -DCMAKE_MACOSX_BUNDLE=OFF \
          -DLLVM_ENABLE_PROJECTS="clang;lld" \
          -DLLVM_TARGETS_TO_BUILD="AArch64" \
          -DLLVM_INCLUDE_TESTS=OFF \
          -DLLVM_INCLUDE_EXAMPLES=OFF \
          -DLLVM_INCLUDE_BENCHMARKS=OFF \
          -DLLVM_BUILD_LLVM_DYLIB=OFF \
          -DLLVM_LINK_LLVM_DYLIB=OFF \
          -DLLVM_ENABLE_ZLIB=OFF \
          -DLLVM_ENABLE_ZSTD=OFF \
          -DLLVM_ENABLE_TERMINFO=OFF \
          -DLLVM_ENABLE_LIBCXX=ON \
          ../llvm-project/llvm

    - name: Build
      run: |
        cd build
        ninja -j$(sysctl -n hw.ncpu) clang lld

    - name: Package
      run: |
        cd build
        mkdir -p package/usr/local/bin
        cp bin/clang bin/clang++ bin/lld package/usr/local/bin/
        tar -czf llvm-for-ios.tar.gz -C package .

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: llvm-for-ios
        path: build/llvm-for-ios.tar.gz
